export const actions = {
	book: {
		DATA_FETCHING: 'DATA_FETCHING',
		DATA_FETCH_ERROR: 'DATA_FETCH_ERROR',
		DATA_FETCHED: 'DATA_FETCHED',
	},
	books: {
		DATA_FETCHING: 'DATA_FETCHING',
		DATA_FETCH_ERROR: 'DATA_FETCH_ERROR',
		DATA_FETCHED: 'DATA_FETCHED',
	},
};
